server:
  port: 8084

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rk_order
    username: postgres
    password: user
  jpa:
    generate-ddl: true
  application:
    name: rk-order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/rk_ecommerce}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8090/realms/rk_ecommerce/protocol/openid-connect/certs}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
grpc:
  server:
    port: 9091
  client:
    sneakerService:
      address: 'static://localhost:9090'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    paymentService:
      address: 'static://localhost:9092'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext