server:
  port: 8084
  error:
    include-stacktrace: never
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rk_order}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:user}
  application:
    name: rk-order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/rk_ecommerce}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8090/realms/rk_ecommerce/protocol/openid-connect/certs}
  liquibase:
    change-log: db/changelog/master.xml
    default-schema: public
    liquibase-schema: public
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
grpc:
  server:
    port: 9091
  client:
    sneakerService:
      address: ${SNEAKER_SERVICE_ADDRESS:static://localhost:9090}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    paymentService:
      address: ${PAYMENT_SERVICE_ADDRESS:static://localhost:9092}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    notificationService:
      address: ${NOTIFICATION_SERVICE_ADDRESS:static://localhost:9093}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    brandsService:
      address: ${BRAND_SERVICE_ADDRESS:static://localhost:9090}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext