server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  application:
    name: rk-gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
              - "http://localhost:4201"
            allowed-headers:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
              - HEAD
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: rk-order-service
          uri: lb://rk-order-service
          predicates:
            - Path=/api/orders/**
        - id: rk-inventory-service
          uri: lb://rk-inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: rk-payment-service
          uri: lb://rk-payment-service
          predicates:
            - Path=/api/payments/**