server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rk_payment}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:user}
  jpa:
    generate-ddl: true
  application:
    name: rk-payment-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

stripe:
  api-key: ${STRIPE_API_KEY:sk_test_cPFnlTE1PZoNYEJAppyCX0st00aIDM9PbS}
client:
  base-url: ${CLIENT_BASE_URL:http://localhost:4201}
grpc:
  server:
    port: 9092
  client:
    orderService:
      address: ${ORDER_SERVICE_ADDRESS:static://localhost:9091}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext