server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rare_kickz}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:user}
  jpa:
    generate-ddl: true
  application:
    name: rk-inventory-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/rk_ecommerce}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8090/realms/rk_ecommerce/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

grpc:
  client:
    orderService:
      address: ${ORDER_SERVICE_ADDRESS:static://localhost:9091}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
