server:
  port: 8083

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rare_kickz}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:user}
  jpa:
    generate-ddl: true
  application:
    name: rk-inventory-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

grpc:
  client:
    orderService:
      address: ${ORDER_SERVICE_ADDRESS:'static://localhost:9091'}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
